### PR TITLE
refactor(formula): align to template formula, add ci

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [x] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [x] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [x] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

NO - because data structure is unchanged (same pillar data works).

### Describe the changes you're proposing

Fully align to Template-formula.
Add CI tests for Ubuntu
Verified on Ubuntu (Centos has issues #45 )

### Documentation checklist

- [x] Updated the `README` (e.g. `Available states`).
- [x] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
@myii could you check this PR looks okay (semantic-release, etc).

**Comment by myii** [comment]
> @myii could you check this PR looks okay (semantic-release, etc).

@noelmcloughlin I'll try to do this over the weekend.

**Comment by myii** [comment]
@noelmcloughlin I couldn't push here but you're welcome to grab this commit if you like (or allow pushing to this PR):

* https://github.com/myii/devstack-formula/commit/53c13360c370758c4a16b3f9ee1063222744d338

Here's the Travis run for it (selected a Py2 & Py3 instance):

* https://travis-ci.org/github/myii/devstack-formula/builds/723350074

**Comment by noelmcloughlin** [comment]
I grabbed that commit, and updated maintainer to contributor

**Comment by myii** [comment]
Merged, thanks @noelmcloughlin.

**Pull request merged**
